<?php

/**
 * Copyright (c) 2025 Fexa AI
 *
 * All Rights Reserved.
 *
 * This module is proprietary software owned by Fexa AI.
 */

namespace PrestaShop\Module\FexaAiConnector\Mcp\Tools;

use PhpMcp\Server\Attributes\McpTool;
use PhpMcp\Server\Attributes\Schema;
use Db;

/**
 * Store + serve the shop's /llms.txt — a machine-readable AEO map of the store
 * for AI answer engines. The markdown is generated by the SaaS (from the catalogue
 * + brand identity) and stored here; it is served at the domain root by the
 * `llms` front controller (the /llms.txt route). Purely additive: writes only to
 * its own table, never touches catalogue data.
 */
class LlmsTxtTools
{
    private const MAX_BYTES = 100000;
    private const TABLE = 'fexa_ai_llms_txt';

    #[McpTool(
        name: 'set_llms_txt',
        description: 'Store the shop /llms.txt markdown, served at the domain root (/llms.txt). Upserts by (id_shop, id_lang).'
    )]
    #[Schema(
        properties: [
            'content' => ['type' => 'string', 'description' => 'Full llms.txt markdown (must contain a "# " H1).'],
            'id_shop' => ['type' => 'integer', 'description' => 'Shop ID (0 = all shops, default)'],
            'id_lang' => ['type' => 'integer', 'description' => 'Language ID (0 = default, default)'],
        ],
        required: ['content']
    )]
    public function setLlmsTxt(string $content, ?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $id_shop = (int) $id_shop;
        $id_lang = (int) $id_lang;
        $content = trim($content);

        if ($content === '') {
            throw new \Exception('content is empty');
        }
        if (strlen($content) > self::MAX_BYTES) {
            throw new \Exception('content too large');
        }
        // Must look like an llms.txt: at least one markdown H1. We never serve
        // arbitrary content at the domain root.
        if (!preg_match('/^#\s+/m', $content)) {
            throw new \Exception('content must contain a markdown H1 (a line starting with "# ")');
        }

        $db = Db::getInstance();
        $c = pSQL($content, true);
        $where = 'id_shop = ' . $id_shop . ' AND id_lang = ' . $id_lang;
        $db->delete(self::TABLE, $where);
        $db->execute(
            'INSERT INTO `' . _DB_PREFIX_ . self::TABLE . '` (id_shop, id_lang, content, is_active) VALUES '
            . '(' . $id_shop . ', ' . $id_lang . ", '" . $c . "', 1)"
        );

        return [
            'status' => 'success',
            'id_shop' => $id_shop,
            'id_lang' => $id_lang,
            'bytes' => strlen($content),
        ];
    }

    #[McpTool(
        name: 'get_llms_txt',
        description: 'Read the stored /llms.txt for a shop (diff / delivery verification).'
    )]
    #[Schema(
        properties: [
            'id_shop' => ['type' => 'integer', 'description' => 'Shop ID (0 = default)'],
            'id_lang' => ['type' => 'integer', 'description' => 'Language ID (0 = default)'],
        ],
        required: []
    )]
    public function getLlmsTxt(?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $id_shop = (int) $id_shop;
        $id_lang = (int) $id_lang;

        $row = Db::getInstance()->getRow(
            'SELECT content, is_active, updated_at FROM `' . _DB_PREFIX_ . self::TABLE . '` '
            . 'WHERE id_shop = ' . $id_shop . ' AND id_lang = ' . $id_lang . ' LIMIT 1'
        );

        return [
            'id_shop' => $id_shop,
            'id_lang' => $id_lang,
            'content' => is_array($row) && isset($row['content']) ? $row['content'] : null,
            'is_active' => is_array($row) ? (int) ($row['is_active'] ?? 0) : 0,
            'updated_at' => is_array($row) ? ($row['updated_at'] ?? null) : null,
        ];
    }

    #[McpTool(
        name: 'delete_llms_txt',
        description: 'Remove the stored /llms.txt for a shop (the route then returns 404).'
    )]
    #[Schema(
        properties: [
            'id_shop' => ['type' => 'integer', 'description' => 'Shop ID (0 = default)'],
            'id_lang' => ['type' => 'integer', 'description' => 'Language ID (0 = default)'],
        ],
        required: []
    )]
    public function deleteLlmsTxt(?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $id_shop = (int) $id_shop;
        $id_lang = (int) $id_lang;

        Db::getInstance()->delete(self::TABLE, 'id_shop = ' . $id_shop . ' AND id_lang = ' . $id_lang);

        return ['status' => 'deleted', 'id_shop' => $id_shop, 'id_lang' => $id_lang];
    }
}
