<?php
/**
 * Copyright (c) 2025 Fexa AI
 *
 * All Rights Reserved.
 *
 * This module is proprietary software owned by Fexa AI.
 *
 * @author    Fexa AI <support@fexaai.com>
 * @copyright 2025 Fexa AI
 * @license   Proprietary
 */

namespace PrestaShop\Module\FexaAiConnector\Mcp\Tools;

use Configuration;
use Exception;
use PhpMcp\Server\Attributes\McpTool;
use PhpMcp\Server\Attributes\Schema;

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * Store + serve the shop's /llms.txt — a machine-readable AEO map of the store for
 * AI answer engines. The markdown is generated by the SaaS (from the catalogue + brand
 * identity) and stored here; the `llms` front controller serves it at the domain root.
 *
 * Stored in PrestaShop **Configuration** (a core table), NOT a dedicated module table.
 * Why: on managed hosting with read/write splitting, writes go to the primary while reads
 * hit a replica. A module table created after the replica was provisioned is absent on the
 * replica, so writes persisted on the primary but every read (get_llms_txt, the /llms.txt
 * controller) returned empty. `configuration` exists on every node and is read on each page
 * load, so writes replicate and reads see them. This mirrors the PS 1.7 lite build.
 */
class LlmsTxtTools
{
    private const KEY = 'FEXA_AI_LLMS_TXT';
    // Configuration.value is a TEXT column (~65535 bytes); stay safely under it.
    private const MAX_BYTES = 60000;

    #[McpTool(
        name: 'set_llms_txt',
        description: 'Store the shop /llms.txt markdown, served at the domain root (/llms.txt). Upserts per shop.'
    )]
    #[Schema(
        properties: [
            'content' => ['type' => 'string', 'description' => 'Full llms.txt markdown (must contain a "# " H1). May be base64-encoded (auto-detected).'],
            'id_shop' => ['type' => 'integer', 'description' => 'Shop ID (0 = all shops, default)'],
            'id_lang' => ['type' => 'integer', 'description' => 'Language ID (kept for compatibility; the file is shop-wide)'],
        ],
        required: ['content']
    )]
    public function setLlmsTxt(string $content, ?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $content = trim($this->maybeDecodeBase64($content));

        if ('' === $content) {
            throw new Exception('content is empty');
        }
        if (strlen($content) > self::MAX_BYTES) {
            throw new Exception('content too large (max '.self::MAX_BYTES.' bytes)');
        }
        // Must look like an llms.txt: at least one markdown H1. We never serve
        // arbitrary content at the domain root.
        if (!preg_match('/^#\s+/m', $content)) {
            throw new Exception('content must contain a markdown H1 (a line starting with "# ")');
        }

        $idShop = ((int) $id_shop) ?: null; // null = global (all shops)
        // Store base64-encoded. PrestaShop's Configuration sanitises HTML-ish characters
        // ('>' → '&gt;', '&' → '&amp;'), which would corrupt the markdown we serve verbatim
        // at /llms.txt. base64 is opaque to that sanitisation — we decode it on read.
        Configuration::updateValue(self::KEY, base64_encode($content), false, null, $idShop);

        return [
            'status' => 'success',
            'id_shop' => (int) $id_shop,
            'bytes' => strlen($content),
        ];
    }

    #[McpTool(
        name: 'get_llms_txt',
        description: 'Read the stored /llms.txt for a shop (diff / delivery verification).'
    )]
    #[Schema(
        properties: [
            'id_shop' => ['type' => 'integer', 'description' => 'Shop ID (0 = default)'],
            'id_lang' => ['type' => 'integer', 'description' => 'Language ID (kept for compatibility)'],
        ],
        required: []
    )]
    public function getLlmsTxt(?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $idShop = ((int) $id_shop) ?: null;

        return [
            'id_shop' => (int) $id_shop,
            'content' => self::readStored($idShop),
        ];
    }

    #[McpTool(
        name: 'delete_llms_txt',
        description: 'Remove the stored /llms.txt for a shop (the route then returns 404).'
    )]
    #[Schema(
        properties: [
            'id_shop' => ['type' => 'integer', 'description' => 'Shop ID (0 = default)'],
            'id_lang' => ['type' => 'integer', 'description' => 'Language ID (kept for compatibility)'],
        ],
        required: []
    )]
    public function deleteLlmsTxt(?int $id_shop = 0, ?int $id_lang = 0): array
    {
        $idShop = ((int) $id_shop) ?: null;
        // Empty value → the front controller returns 404.
        Configuration::updateValue(self::KEY, '', true, null, $idShop);

        return ['status' => 'deleted', 'id_shop' => (int) $id_shop];
    }

    /** Decode a WAF-safe base64 transport. Real llms.txt markdown always contains spaces,
     *  '#' and newlines (none of which are in the base64 alphabet), so a payload that is a
     *  single pure base64 token is the SaaS sending the content encoded to dodge web-app
     *  firewalls (e.g. Atomicorp rule 360151 flags the markdown link syntax "[x](y)" as a
     *  PHP-injection attempt). Plain markdown is returned untouched. */
    private function maybeDecodeBase64(string $content): string
    {
        $t = trim($content);
        if ('' !== $t && preg_match('/^[A-Za-z0-9+\/]+={0,2}$/', $t)) {
            $decoded = base64_decode($t, true);
            if (false !== $decoded && '' !== $decoded) {
                return $decoded;
            }
        }

        return $content;
    }

    /** Read the stored /llms.txt: base64-decode the Configuration value (how setLlmsTxt
     *  stores it). Tolerates a legacy raw (non-base64) value by returning it as-is, so an
     *  upgrade keeps serving the old content until the next push overwrites it. Shared with
     *  the front controller so both decode identically. */
    public static function readStored(?int $idShop): ?string
    {
        $raw = Configuration::get(self::KEY, null, null, $idShop);
        if (false === $raw || null === $raw || '' === $raw) {
            return null;
        }
        $decoded = base64_decode((string) $raw, true);

        return (false !== $decoded && '' !== $decoded) ? $decoded : (string) $raw;
    }
}
